### ISSUE TITLE
org.owasp.dependencycheck.Engine: Unexpected exception occurred initializing CPE Analyzer.

### ISSUE THREAD

**Issue by Juholei** [rm-hull/lein-nvd#34] opened 2019-06-04 13:12 UTC
We have a fairly large project where we are trying to add lein-nvd. Unfortunately it doesn't work in our project and fails due to Unexpected exception occurred initializing CPE Analyzer. I haven't been figured any way to work around this. Any idea whether this is due to some dependency or our code?

```
ERROR 2019-06-04 16:08:51.052 [] o.o.d.analyzer.AssemblyAnalyzer: ----------------------------------------------------
ERROR 2019-06-04 16:08:51.054 [] o.o.d.analyzer.AssemblyAnalyzer: .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.
ERROR 2019-06-04 16:08:51.054 [] o.o.d.analyzer.AssemblyAnalyzer: ----------------------------------------------------
ERROR 2019-06-04 16:08:51.238 [] org.owasp.dependencycheck.Engine: Unexpected exception occurred initializing CPE Analyzer.
Exception in thread "main" Syntax error compiling at (/private/var/folders/zs/xwx9c01d2nd_40fjjk9f_b4c0000gp/T/form-init8886338634330637156.clj:1:125).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	Unexpected Exception
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
	at nvd.task.check$scan_and_analyze.invokeStatic(check.clj:43)
	at nvd.task.check$scan_and_analyze.invoke(check.clj:38)
	at nvd.task.check$_main.invokeStatic(check.clj:54)
	at nvd.task.check$_main.invoke(check.clj:51)
	at user$eval22080.invokeStatic(form-init8886338634330637156.clj:1)
	at user$eval22080.invoke(form-init8886338634330637156.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
Subprocess failed
```

**Comment by rm-hull** [comment] 2019-06-04 13:17
Can you create a dummy `project.clj` which has the same dependencies as your project so we can try and reproduce this issue?

**Comment by rm-hull** [comment] 2019-06-04 13:19
Also, do you have any extra nvd config flags set in either your user profile or `project.clj` ?

**Comment by Juholei** [comment] 2019-06-04 13:49
There isn't any configuration done. In a fresh project with the same dependencies it seems to end up in the same error as in #33. I figured out that I'd start stripping away some dependencies to see if it is some of them causing it and it seems now if I remove [clojurewerkz/elastisch "2.2.2"] from the dependencies, the analysis succeeds.

project.clj containing only this `(defproject dummy-project "1.0.0"
  :dependencies [[clojurewerkz/elastisch "2.2.2"]]
:plugins [[lein-nvd "1.0.0"]])` ends with the error `Exception in thread "main" org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	Unexpected Exception, compiling:(/private/var/folders/zs/xwx9c01d2nd_40fjjk9f_b4c0000gp/T/form-init824973952916588961.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	Unexpected Exception
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
	at nvd.task.check$scan_and_analyze.invoke(check.clj:43)
	at nvd.task.check$_main.invoke(check.clj:54)
	at user$eval516.invoke(form-init824973952916588961.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more`

**Comment by rm-hull** [comment] 2019-06-13 07:15
Thanks for the reproducible test case ... I will investigate further

**Comment by keveri** [comment] 2019-07-29 10:40
I hope this helps. Thanks for working on this library!

## Exceptions

I had similar issues with `monger` library. The exception seems to be caused by guava library version 18.0. In monger's case guava comes from `clojurewerkz/support`:

```
$ lein deps :tree
...
[com.novemberain/monger "3.5.0"]
   [clojurewerkz/support "1.1.0"]
     [com.google.guava/guava "18.0"]
...
```

The exception can be avoided by using the latest support library version as it uses a different version of guava:
```
- [com.novemberain/monger "3.5.0"]
+ [com.novemberain/monger "3.5.0" :exclude clojurewerkz/support]
+ [clojurewerkz/support "1.5.0"] ;this overrides the problematic monger dependency
```

After the change:
```
$ lein deps :tree
[clojurewerkz/support "1.5.0"]
   [com.google.guava/guava "21.0"]
```

*I stopped here and didn't look further on why older guava version causes the exceptions.*

## Elastisch

@Juholei `clojurewerkz/elastisch` also uses the support library but it actually excludes the guava dependency for it already. The guava (version 18) dependency comes from `org.elasticsearch/elasticsearch`. This old guava version might be the issue for you also.

Even latest elastisch seems to use an old version of elasticsearch. Might be worth a try to override it or guava.

**Comment by vemv** [comment] 2019-08-01 01:43
Experiencing this one as well, it's frustrating that no useful info is printed.

@rm-hull: I would suggest that you specifically catch `ExceptionCollection`, accessing its [getExceptions() ](https://github.com/jeremylong/DependencyCheck/blob/2fbee6714e115aee052a58436d85ed433bb1e36c/core/src/main/java/org/owasp/dependencycheck/exception/ExceptionCollection.java#L127) method, so each of the actual exceptions get printed.

You could compose those into an `ex-info`'s data and throw that.

**Comment by vemv** [comment] 2019-08-06 12:28
> I would suggest that you specifically catch ExceptionCollection, accessing its getExceptions() method, so each of the actual exceptions get printed.

Any luck with this? I could contribute a PR.

**Comment by rm-hull** [comment] 2019-08-06 13:24
Happy to accept PRs - Im not going to be able to look at this until late August - on vacation at the moment

**Comment by vemv** [comment] 2019-10-01 21:14
Note that https://github.com/rm-hull/lein-nvd/pull/42 was merged as 1.3.0, so if this issue is still valid, it can be reproduced far more cleanly now.

**Comment by Juholei** [comment] 2019-12-30 14:09
This doesn't seem to happen anymore on 1.3.1.

**Comment by rm-hull** [comment] 2020-12-27 23:50
[closing as per @Juholei's last comment]

Please re-open if you affected by this

**Closed by rm-hull** 2020-12-27 23:50 UTC
